### ISSUE TITLE
No Modman file

### ISSUE THREAD

**Issue by mwarrink** [merchantprotocol/M1-developer-toolbar#8]
Hello,

Your Developer toolbar is very nice!
But unfortunately I can't install this through modman, because you haven't pushed the modman file.

Good luck,
Martijn

**Comment by jonathonbyrdziak** [comment]
Sorry about that @mwarrink I'll look into it.

**Comment by jonathonbyrdziak** [comment]
#### Expectations
- [x] [Setup the modman configuration file.](https://github.com/colinmollenhour/modman/wiki/Tutorial)
